[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
lib_deps = 
	ayushsharma82/ElegantOTA@3.1.6
	bodmer/TFT_eSPI@^2.5.43
build_flags = 
    -D USER_SETUP_LOADED
	-D ST7789_DRIVER
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=240
	-D TFT_MOSI=13
	-D TFT_SCLK=14
	-D TFT_DC=5
	-D TFT_RST=4
	-D TFT_BL=16
	-D SPI_FREQUENCY=40000000
	-D TFT_CS=-1
    -D LOAD_GLCD
    -D LOAD_FONT2
    -D LOAD_FONT4
    -D LOAD_FONT6
    -D LOAD_FONT7
    -D LOAD_FONT8
