[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
lib_deps = 
    ayushsharma82/ElegantOTA@3.1.6
    bodmer/TFT_eSPI@^2.5.43
    bodmer/TJpg_Decoder @ ~1.1.0
    bblanchon/ArduinoJson @ ^7.4.2
build_flags = 
    -D USER_SETUP_LOADED
    -D ST7789_DRIVER
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_DC=27
    -D TFT_RST=26
    -D TFT_BL=25
    -D SPI_FREQUENCY=40000000
    -D TFT_CS=-1
    -D LOAD_GLCD
    -D LOAD_FONT2
    -D LOAD_FONT4
    -D LOAD_FONT6
    -D LOAD_FONT7
    -D LOAD_FONT8

; Nama Pin TFT,Pin ESP32 (GPIO),Keterangan
; VCC,3.3V,"Wajib 3.3V, jangan 5V langsung ke chip!"
; GND,GND,Ground bersama.
; SCL / SCLK,GPIO 18,Jalur Clock SPI.
; SDA / MOSI,GPIO 23,Jalur Data SPI.
; RES / RST,GPIO 4,Reset layar.
; DC / RS,GPIO 2,Data/Command selection.
; BLK / BL,GPIO 5,Backlight (bisa diatur lewat kodingan).

; Pin,Status Wajib,Komponen,Keterangan
; EN (RST),HIGH,Resistor 10k ke 3.3V,Chip Aktif
; GPIO 0,HIGH,Resistor 10k ke 3.3V,Mode Running (Normal)
; GPIO 2,LOW,(Internal Pull-down),Harus Low untuk masuk mode Flash
; GPIO 15,HIGH,(Internal Pull-up),Mengontrol output log