@host = 192.168.2.182

# REST API Endpoints for Power Meter & Server Monitor

### System Info
GET http://{{host}}/sys/info

###

### Format Filesystem (Hapus data gambar lama di LittleFS)
GET http://{{host}}/sys/format

###

### Web OTA Firmware Upload (Multipart POST)
# POST http://{{host}}/update
# Content-Type: multipart/form-data; boundary=----WebKitFormBoundary
# (Atau langsung upload via web browser di http://{{host}}/)

###

### Root Page (WiFi Config)
GET http://{{host}}/

###

### WiFi - Get Saved WiFi Data
GET http://{{host}}/wifi/data

###

### WiFi - Add WiFi
POST http://{{host}}/wifi/add
Content-Type: application/x-www-form-urlencoded

ssid=MyWiFi&pass=mypassword&static=false

###

### WiFi - Delete WiFi
POST http://{{host}}/wifi/delete
Content-Type: application/x-www-form-urlencoded

ssid=MyWiFi

###

### WiFi - Test WiFi Connection
POST http://{{host}}/wifi/test
Content-Type: application/x-www-form-urlencoded

ssid=MyWiFi&pass=mypassword

###

### LCD - Set Backlight (0-255)
GET http://{{host}}/lcd/backlight?value=200

###

### LCD - Clear Display
GET http://{{host}}/lcd/clear

###